onboarding = false

[keys]
prefix = "ctrl+g"
help = "prefix+ctrl+/"
reload_config = "prefix+shift+z"
goto = "prefix+enter"
workspace_picker = "prefix+ctrl+w"
new_workspace = "prefix+shift+n"
rename_workspace = "prefix+shift+r"
close_workspace = "prefix+shift+w"
new_worktree = "prefix+shift+c"
open_worktree = "prefix+shift+o"
remove_worktree = "prefix+shift+d"
previous_workspace = "prefix+shift+["
next_workspace = "prefix+shift+]"
previous_agent = "prefix+p"
next_agent = "prefix+n"
navigate_workspace_up = ["up", "k"]
navigate_workspace_down = ["down", "j"]
new_tab = "prefix+ctrl+t"
rename_tab = "prefix+ctrl+r"
next_tab = "prefix+]"
previous_tab = "prefix+["
focus_agent = "prefix+1..9"
close_tab = ""
copy_mode = "prefix+space"
split_vertical = "prefix+ctrl+v"
split_horizontal = "prefix+ctrl+s"
focus_pane_left = "prefix+ctrl+h"
focus_pane_down = "prefix+ctrl+j"
focus_pane_up = "prefix+ctrl+k"
focus_pane_right = "prefix+ctrl+l"
cycle_pane_next = ""
cycle_pane_previous = ""
last_pane = "prefix+tab"

[[keys.command]]
key = "prefix+g"
type = "plugin_action"
command = "persiyanov.reviewr.open"
description = "open Herdr Reviewer"

[[keys.command]]
key = "prefix+G"
type = "popup"
command = "lazygit"
description = "open LazyGit"
width = "80%"
height = "80%"

[[keys.command]]
key = "prefix+P"
type = "plugin_action"
command = "ray.plugin-manager.open"
description = "open plugin manager"

[ui.toast]
delivery = "herdr"

[ui]
show_agent_labels_on_pane_borders = true

agent_panel_sort = "spaces"
[theme]
name = "catppuccin"
auto_switch = false

[experimental]
kitty_graphics = true
